export const SAVE_EVENT_START = 'SAVE_EVENT_START'
export const SAVE_EVENT_SUCCESS = 'SAVE_EVENT_SUCCESS'
export const SAVE_EVENT_FAIL = 'SAVE_EVENT_FAIL'

export const UPDATE_TEXTFIELD_VALUE = 'UPDATE_TEXTFIELD_VALUE'
export const UPDATE_DATE_VALUE = 'UPDATE_DATE_VALUE'
export const UPDATE_FIELD_ERROR = 'UPDATE_FIELD_ERROR'

export const RESET_FORM = 'RESET_FORM'